[package]
name = "syn"
version = "0.0.1"
authors = ["Klemen Košir <klemen.kosir@kream.io>"]
license = "MIT"
edition = "2018"

[dependencies]
clap = { version = "2.33", default-features = false }
toml = { version = "0.5", features = ["preserve_order"] }
