version: 2.1

commands:
  setup:
    steps:
      - run:
          name: Setup environment
          command: |
            echo "`rustc --version | cut -d' ' -f2`" > ~/.version

  version:
    steps:
      - run:
          name: Version information
          command: |
            rustc --version
            cargo --version
            rustup --version

  save-cache:
    steps:
      - save_cache:
          key: cache-{{ checksum "~/.version" }}-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps

  load-cache:
    steps:
      - restore_cache:
          key: cache-{{ checksum "~/.version" }}-{{ checksum "Cargo.lock" }}

jobs:
  style:
    docker:
      - image: circleci/rust:1

    steps:
      - setup
      - version
      - checkout
      - load-cache

      - run:
          name: rustfmt
          command: |
            rustup component add rustfmt
            cargo fmt --all -- --check

      - run:
          name: rust-clippy
          command: |
            rustup component add clippy
            cargo clippy -- -D warnings

  build:
    docker:
      - image: circleci/rust:1

    steps:
      - setup
      - version
      - checkout
      - load-cache
      - run: cargo build
      - save-cache

  test:
    docker:
      - image: circleci/rust:1

    steps:
      - setup
      - version
      - checkout
      - load-cache
      - run: cargo test

workflows:
  version: 2

  commit:
    jobs:
      - style
      - build
      - test:
          requires:
            - build
