name = "dragon"
description = "Example from the Dragon Book"
start_symbol = "E"

[rules]
E = [
    "E + T",
    "T",
]

T = [
    "T * F",
    "F",
]

F = [
    "( E )",
    "int",
]

[tokens]
int = "[0-9]+"

[ignore]
whitespace = "[ \t\r\n]*"
