---
name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Rust"
        uses: dtolnay/rust-toolchain@stable

      - name: "Build"
        run: cargo build

  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Rust"
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: "Run Rustfmt"
        run: cargo fmt --all --check

      - name: "Run Clippy"
        run: cargo clippy -- -D warnings
